In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/lagos_weather_transformed.csv")
df.head()

,date,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum
0,2006-01-01,29.4,27.4,25.9,25.1,24.6,23.7,93,85,72,1010.0,1007.8,1005.7,15.1,10.4,6.9,0.6
1,2006-01-02,31.0,27.8,26.1,25.0,24.4,23.8,90,82,67,1009.9,1007.5,1005.0,16.8,12.3,8.9,1.1
2,2006-01-03,31.1,27.9,26.1,24.9,24.3,23.2,92,82,63,1008.8,1006.7,1004.8,19.1,13.9,9.3,0.8
3,2006-01-04,30.2,27.7,26.1,24.5,24.0,23.4,90,81,67,1007.6,1005.8,1003.6,16.6,13.9,11.2,1.4
4,2006-01-05,30.0,27.4,25.5,24.6,24.3,23.8,92,83,69,1007.7,1005.6,1003.6,16.1,10.6,4.1,0.8

In [2]:
df.shape

(7305, 17)

In [3]:
df["date"] = pd.to_datetime(df["date"])

In [4]:
from datetime import datetime

monthly_df = df.copy()

monthly_df["month"] = monthly_df["date"].dt.to_period("M")

monthly_df.head()

,date,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum,month
0,2006-01-01,29.4,27.4,25.9,25.1,24.6,23.7,93,85,72,1010.0,1007.8,1005.7,15.1,10.4,6.9,0.6,2006-01
1,2006-01-02,31.0,27.8,26.1,25.0,24.4,23.8,90,82,67,1009.9,1007.5,1005.0,16.8,12.3,8.9,1.1,2006-01
2,2006-01-03,31.1,27.9,26.1,24.9,24.3,23.2,92,82,63,1008.8,1006.7,1004.8,19.1,13.9,9.3,0.8,2006-01
3,2006-01-04,30.2,27.7,26.1,24.5,24.0,23.4,90,81,67,1007.6,1005.8,1003.6,16.6,13.9,11.2,1.4,2006-01
4,2006-01-05,30.0,27.4,25.5,24.6,24.3,23.8,92,83,69,1007.7,1005.6,1003.6,16.1,10.6,4.1,0.8,2006-01

In [5]:
monthly_weather = (
    monthly_df
    .groupby("month")
    .agg({
        "temperature_2m_max": "mean",
        "temperature_2m_mean": "mean",
        "temperature_2m_min": "mean",

        "dew_point_2m_max": "mean",
        "dew_point_2m_mean": "mean",
        "dew_point_2m_min": "mean",

        "relative_humidity_2m_max": "mean",
        "relative_humidity_2m_mean": "mean",
        "relative_humidity_2m_min": "mean",

        "surface_pressure_max": "mean",
        "surface_pressure_mean": "mean",
        "surface_pressure_min": "mean",

        "wind_speed_10m_max": "mean",
        "wind_speed_10m_mean": "mean",
        "wind_speed_10m_min": "mean",

        "precipitation_sum": "sum"
    })
    .reset_index()
)
print(monthly_weather.shape)
monthly_weather.head()

(240, 17)

,month,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum
0,2006-01,29.938710,27.432258,25.893548,24.764516,24.377419,23.819355,91.903226,83.709677,71.548387,1010.096774,1008.080645,1006.048387,16.654839,12.516129,8.535484,58.2
1,2006-02,30.260714,27.914286,26.439286,24.928571,24.503571,24.053571,89.785714,81.964286,71.214286,1010.135714,1008.042857,1005.960714,17.950000,14.117857,9.789286,81.9
2,2006-03,30.577419,28.161290,26.551613,24.787097,24.380645,23.951613,88.161290,80.290323,69.387097,1010.816129,1008.635484,1006.780645,17.570968,13.961290,9.858065,89.4
3,2006-04,30.330000,28.050000,26.576667,25.126667,24.723333,24.256667,89.633333,82.400000,72.000000,1009.793333,1007.723333,1005.820000,16.593333,12.713333,8.260000,132.6
4,2006-05,28.545161,26.629032,24.980645,24.790323,24.174194,23.645161,94.032258,86.548387,78.483871,1012.370968,1010.358065,1008.558065,13.932258,8.967742,4.087097,270.6

In [6]:
monthly_weather["next_month_precipitation"] = (
    monthly_weather["precipitation_sum"].shift(-1)
)

monthly_weather = monthly_weather.dropna(
    subset=["next_month_precipitation"]
).reset_index(drop=True)

In [7]:
print(monthly_weather.shape)
monthly_weather.head()

(239, 18)

,month,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum,next_month_precipitation
0,2006-01,29.938710,27.432258,25.893548,24.764516,24.377419,23.819355,91.903226,83.709677,71.548387,1010.096774,1008.080645,1006.048387,16.654839,12.516129,8.535484,58.2,81.9
1,2006-02,30.260714,27.914286,26.439286,24.928571,24.503571,24.053571,89.785714,81.964286,71.214286,1010.135714,1008.042857,1005.960714,17.950000,14.117857,9.789286,81.9,89.4
2,2006-03,30.577419,28.161290,26.551613,24.787097,24.380645,23.951613,88.161290,80.290323,69.387097,1010.816129,1008.635484,1006.780645,17.570968,13.961290,9.858065,89.4,132.6
3,2006-04,30.330000,28.050000,26.576667,25.126667,24.723333,24.256667,89.633333,82.400000,72.000000,1009.793333,1007.723333,1005.820000,16.593333,12.713333,8.260000,132.6,270.6
4,2006-05,28.545161,26.629032,24.980645,24.790323,24.174194,23.645161,94.032258,86.548387,78.483871,1012.370968,1010.358065,1008.558065,13.932258,8.967742,4.087097,270.6,275.3

In [8]:
target = "next_month_precipitation"

features = [
    "temperature_2m_max",
    "temperature_2m_mean",
    "temperature_2m_min",

    "dew_point_2m_max",
    "dew_point_2m_mean",
    "dew_point_2m_min",

    "relative_humidity_2m_max",
    "relative_humidity_2m_mean",
    "relative_humidity_2m_min",

    "surface_pressure_max",
    "surface_pressure_mean",
    "surface_pressure_min",

    "wind_speed_10m_max",
    "wind_speed_10m_mean",
    "wind_speed_10m_min",

    "precipitation_sum"
]

X = monthly_weather[features]
y = monthly_weather[target]

In [9]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (239, 16)
y shape: (239,)

In [10]:
print("Missing values in X:")
print(X.isnull().sum())

print("\nMissing values in y:")
print(y.isnull().sum())

Missing values in X:
temperature_2m_max           0
temperature_2m_mean          0
temperature_2m_min           0
dew_point_2m_max             0
dew_point_2m_mean            0
dew_point_2m_min             0
relative_humidity_2m_max     0
relative_humidity_2m_mean    0
relative_humidity_2m_min     0
surface_pressure_max         0
surface_pressure_mean        0
surface_pressure_min         0
wind_speed_10m_max           0
wind_speed_10m_mean          0
wind_speed_10m_min           0
precipitation_sum            0
dtype: int64

Missing values in y:
0

In [49]:
y.isna().sum()

0

In [11]:
X_train = X.iloc[:-24]
X_test = X.iloc[-24:]

y_train = y.iloc[:-24]
y_test = y.iloc[-24:]

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (215, 16)
X_test: (24, 16)
y_train: (215,)
y_test: (24,)

In [12]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [13]:
print(y_pred[:10])

[ 22.182   58.0005  52.426  127.6975  92.119  207.2575 209.9755 176.9465
 204.3015 181.905 ]

In [17]:
y_test.head(10).values

array([ 12.9,  41.2, 100.8,  76. , 103.1, 221.7, 171.2,  94.4, 192.8,
       190.7])

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE:  {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²:   {r2:.2f}")

MAE:  44.43
RMSE: 57.54
R²:   0.48

In [19]:
feature_importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values(
    by="importance",
    ascending=False
)

feature_importance

                      feature  importance
15          precipitation_sum    0.407745
13        wind_speed_10m_mean    0.101406
11       surface_pressure_min    0.091020
12         wind_speed_10m_max    0.048349
14         wind_speed_10m_min    0.042631
2          temperature_2m_min    0.040838
6    relative_humidity_2m_max    0.035943
9        surface_pressure_max    0.032821
5            dew_point_2m_min    0.032230
8    relative_humidity_2m_min    0.029023
4           dew_point_2m_mean    0.028346
10      surface_pressure_mean    0.027878
7   relative_humidity_2m_mean    0.024028
1         temperature_2m_mean    0.023161
0          temperature_2m_max    0.021633
3            dew_point_2m_max    0.012947

In [20]:
comparison = monthly_weather.iloc[-24:][
    ["month", "precipitation_sum", "next_month_precipitation"]
].copy()

comparison["predicted_precipitation"] = y_pred

comparison["error"] = (
    comparison["predicted_precipitation"]
    - comparison["next_month_precipitation"]
)

comparison

,month,precipitation_sum,next_month_precipitation,predicted_precipitation,error
215,2023-12,13.9,12.9,22.1820,9.2820
216,2024-01,12.9,41.2,58.0005,16.8005
217,2024-02,41.2,100.8,52.4260,-48.3740
218,2024-03,100.8,76.0,127.6975,51.6975
219,2024-04,76.0,103.1,92.1190,-10.9810
220,2024-05,103.1,221.7,207.2575,-14.4425
221,2024-06,221.7,171.2,209.9755,38.7755
222,2024-07,171.2,94.4,176.9465,82.5465
223,2024-08,94.4,192.8,204.3015,11.5015
224,2024-09,192.8,190.7,181.9050,-8.7950
225,2024-10,190.7,48.1,150.3000,102.2000
226,2024-11,48.1,9.4,22.5495,13.1495
227,2024-12,9.4,23.8,21.5525,-2.2475
228,2025-01,23.8,51.3,24.7685,-26.5315
229,2025-02,51.3,96.4,47.1285,-49.2715
230,2025-03,96.4,173.7,111.4080,-62.2920
231,2025-04,173.7,195.4,208.4710,13.0710
232,2025-05,195.4,334.8,183.9315,-150.8685
233,2025-06,334.8,106.4,180.9585,74.5585
234,2025-07,106.4,106.0,165.4240,59.4240
235,2025-08,106.0,224.9,151.8100,-73.0900
236,2025-09,224.9,192.0,202.3725,10.3725
237,2025-10,192.0,69.0,157.7115,88.7115
238,2025-11,69.0,71.8,24.4170,-47.3830

In [ ]:
comparison[
    ["month", "next_month_precipitation",
     "predicted_precipitation", "error"]
]