In [41]:
import pandas as pd

df = pd.read_csv("../data/processed/lagos_weather_transformed.csv")
df.head()

,date,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum
0,2006-01-01,29.4,27.4,25.9,25.1,24.6,23.7,93,85,72,1010.0,1007.8,1005.7,15.1,10.4,6.9,0.6
1,2006-01-02,31.0,27.8,26.1,25.0,24.4,23.8,90,82,67,1009.9,1007.5,1005.0,16.8,12.3,8.9,1.1
2,2006-01-03,31.1,27.9,26.1,24.9,24.3,23.2,92,82,63,1008.8,1006.7,1004.8,19.1,13.9,9.3,0.8
3,2006-01-04,30.2,27.7,26.1,24.5,24.0,23.4,90,81,67,1007.6,1005.8,1003.6,16.6,13.9,11.2,1.4
4,2006-01-05,30.0,27.4,25.5,24.6,24.3,23.8,92,83,69,1007.7,1005.6,1003.6,16.1,10.6,4.1,0.8

In [42]:
df.shape

(7305, 17)

In [43]:
df["date"] = pd.to_datetime(df["date"])

In [44]:
from datetime import datetime

monthly_df = df.copy()

monthly_df["month"] = monthly_df["date"].dt.to_period("M")

monthly_df.head()

,date,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum,month
0,2006-01-01,29.4,27.4,25.9,25.1,24.6,23.7,93,85,72,1010.0,1007.8,1005.7,15.1,10.4,6.9,0.6,2006-01
1,2006-01-02,31.0,27.8,26.1,25.0,24.4,23.8,90,82,67,1009.9,1007.5,1005.0,16.8,12.3,8.9,1.1,2006-01
2,2006-01-03,31.1,27.9,26.1,24.9,24.3,23.2,92,82,63,1008.8,1006.7,1004.8,19.1,13.9,9.3,0.8,2006-01
3,2006-01-04,30.2,27.7,26.1,24.5,24.0,23.4,90,81,67,1007.6,1005.8,1003.6,16.6,13.9,11.2,1.4,2006-01
4,2006-01-05,30.0,27.4,25.5,24.6,24.3,23.8,92,83,69,1007.7,1005.6,1003.6,16.1,10.6,4.1,0.8,2006-01

In [45]:
monthly_weather = (
    monthly_df
    .groupby("month")
    .agg({
        "temperature_2m_max": "mean",
        "temperature_2m_mean": "mean",
        "temperature_2m_min": "mean",

        "dew_point_2m_max": "mean",
        "dew_point_2m_mean": "mean",
        "dew_point_2m_min": "mean",

        "relative_humidity_2m_max": "mean",
        "relative_humidity_2m_mean": "mean",
        "relative_humidity_2m_min": "mean",

        "surface_pressure_max": "mean",
        "surface_pressure_mean": "mean",
        "surface_pressure_min": "mean",

        "wind_speed_10m_max": "mean",
        "wind_speed_10m_mean": "mean",
        "wind_speed_10m_min": "mean",

        "precipitation_sum": "sum"
    })
    .reset_index()
)
print(monthly_weather.shape)
monthly_weather.head()

(240, 17)

,month,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum
0,2006-01,29.938710,27.432258,25.893548,24.764516,24.377419,23.819355,91.903226,83.709677,71.548387,1010.096774,1008.080645,1006.048387,16.654839,12.516129,8.535484,58.2
1,2006-02,30.260714,27.914286,26.439286,24.928571,24.503571,24.053571,89.785714,81.964286,71.214286,1010.135714,1008.042857,1005.960714,17.950000,14.117857,9.789286,81.9
2,2006-03,30.577419,28.161290,26.551613,24.787097,24.380645,23.951613,88.161290,80.290323,69.387097,1010.816129,1008.635484,1006.780645,17.570968,13.961290,9.858065,89.4
3,2006-04,30.330000,28.050000,26.576667,25.126667,24.723333,24.256667,89.633333,82.400000,72.000000,1009.793333,1007.723333,1005.820000,16.593333,12.713333,8.260000,132.6
4,2006-05,28.545161,26.629032,24.980645,24.790323,24.174194,23.645161,94.032258,86.548387,78.483871,1012.370968,1010.358065,1008.558065,13.932258,8.967742,4.087097,270.6

In [46]:
monthly_weather["next_month_precipitation"] = (
    monthly_weather["precipitation_sum"].shift(-1)
)

monthly_weather = monthly_weather.dropna(
    subset=["next_month_precipitation"]
).reset_index(drop=True)

In [47]:
print(monthly_weather.shape)
monthly_weather.tail()

(239, 18)

,month,temperature_2m_max,temperature_2m_mean,temperature_2m_min,dew_point_2m_max,dew_point_2m_mean,dew_point_2m_min,relative_humidity_2m_max,relative_humidity_2m_mean,relative_humidity_2m_min,surface_pressure_max,surface_pressure_mean,surface_pressure_min,wind_speed_10m_max,wind_speed_10m_mean,wind_speed_10m_min,precipitation_sum,next_month_precipitation
234,2025-07,28.093548,25.538710,23.932258,22.858065,22.303226,21.625806,92.032258,82.677419,69.193548,1015.716129,1013.948387,1012.038710,16.561290,11.641935,7.209677,106.4,106.0
235,2025-08,27.683871,25.193548,23.693548,22.683871,22.177419,21.567742,92.741935,83.806452,70.451613,1015.416129,1013.441935,1011.535484,16.490323,11.748387,7.951613,106.0,224.9
236,2025-09,28.436667,25.686667,23.963333,23.290000,22.763333,22.090000,93.733333,84.500000,70.300000,1014.673333,1012.666667,1010.640000,13.713333,8.756667,4.030000,224.9,192.0
237,2025-10,29.500000,26.564516,24.558065,24.425806,23.541935,22.583871,94.290323,84.064516,68.709677,1013.300000,1011.306452,1009.335484,11.487097,6.735484,2.406452,192.0,69.0
238,2025-11,30.620000,27.396667,24.996667,25.016667,24.146667,23.033333,95.166667,83.066667,65.600000,1012.460000,1010.366667,1008.310000,12.086667,7.020000,2.100000,69.0,71.8

In [48]:
target = "next_month_precipitation"

features = [
    "temperature_2m_max",
    "temperature_2m_mean",
    "temperature_2m_min",

    "dew_point_2m_max",
    "dew_point_2m_mean",
    "dew_point_2m_min",

    "relative_humidity_2m_max",
    "relative_humidity_2m_mean",
    "relative_humidity_2m_min",

    "surface_pressure_max",
    "surface_pressure_mean",
    "surface_pressure_min",

    "wind_speed_10m_max",
    "wind_speed_10m_mean",
    "wind_speed_10m_min",
    "precipitation_sum"

]

X = monthly_weather[features]
y = monthly_weather[target]

In [49]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (239, 16)
y shape: (239,)

In [50]:
print(X.columns
    .tolist())
print(y.name)

['temperature_2m_max', 'temperature_2m_mean', 'temperature_2m_min', 'dew_point_2m_max', 'dew_point_2m_mean', 'dew_point_2m_min', 'relative_humidity_2m_max', 'relative_humidity_2m_mean', 'relative_humidity_2m_min', 'surface_pressure_max', 'surface_pressure_mean', 'surface_pressure_min', 'wind_speed_10m_max', 'wind_speed_10m_mean', 'wind_speed_10m_min', 'precipitation_sum']
next_month_precipitation

In [51]:
print("Missing values in X:")
print(X.isnull().sum())

print("\nMissing values in y:")
print(y.isnull().sum())

Missing values in X:
temperature_2m_max           0
temperature_2m_mean          0
temperature_2m_min           0
dew_point_2m_max             0
dew_point_2m_mean            0
dew_point_2m_min             0
relative_humidity_2m_max     0
relative_humidity_2m_mean    0
relative_humidity_2m_min     0
surface_pressure_max         0
surface_pressure_mean        0
surface_pressure_min         0
wind_speed_10m_max           0
wind_speed_10m_mean          0
wind_speed_10m_min           0
precipitation_sum            0
dtype: int64

Missing values in y:
0

In [52]:
y.isna().sum()

0

In [53]:
split_index = int(len(X) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print("Training observations:", len(X_train))
print("Testing observations:", len(X_test))

Training observations: 191
Testing observations: 48

In [54]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [55]:
print(y_pred[:10])

[ 34.834   38.3305  57.7975  94.243  198.4445 204.8995 207.495  174.9305
 187.2995 139.377 ]

In [56]:
y_test.head(10).values

array([ 16.8,  16.7,  76.2, 108. , 120.4, 275.1, 145.8, 102.9, 160.6,
       132.1])

In [57]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE:  {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²:   {r2:.2f}")

MAE:  46.33
RMSE: 58.74
R²:   0.48

In [58]:
feature_importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values(
    by="importance",
    ascending=False
)

feature_importance

                      feature  importance
15          precipitation_sum    0.407217
11       surface_pressure_min    0.091880
13        wind_speed_10m_mean    0.086270
12         wind_speed_10m_max    0.050794
14         wind_speed_10m_min    0.050345
2          temperature_2m_min    0.045254
9        surface_pressure_max    0.039945
6    relative_humidity_2m_max    0.037806
4           dew_point_2m_mean    0.029696
8    relative_humidity_2m_min    0.028191
10      surface_pressure_mean    0.027724
5            dew_point_2m_min    0.026342
7   relative_humidity_2m_mean    0.023118
1         temperature_2m_mean    0.022959
0          temperature_2m_max    0.017172
3            dew_point_2m_max    0.015286